colors:
  foreground: &foreground "#A51FFF"
  background: &background default
  current_line: &current_line mediumvioletred
  selection: &selection darkred
  comment: &comment silver
  cyan: &cyan "#5E1191" # secondary
  green: &green forestgreen
  yellow: &yellow orchid # active color
  orange: &orange orange
  magenta: &magenta "#d33682"
  blue: &blue darkcyan # blue
  red: &red "#dc322f"

# Skin...
k9s:
  body:
    fgColor: *foreground
    bgColor: *background
    logoColor: *blue
  prompt:
    fgColor: *foreground
    bgColor: *background
    suggestColor: *orange
  info:
    fgColor: *magenta
    sectionColor: *foreground
  dialog:
    fgColor: *foreground
    bgColor: *background
    buttonFgColor: *foreground
    buttonBgColor: *magenta
    buttonFocusFgColor: white
    buttonFocusBgColor: *cyan
    labelFgColor: *orange
    fieldFgColor: *foreground
  help:
    fgColor: *blue
    bgColor: *background
    keyColor: *cyan
    numKeyColor: *magenta
    sectionColor: *red
  frame:
    border:
      fgColor: *selection
      focusColor: *foreground
    menu:
      fgColor: red
      keyColor: *magenta
      numKeyColor: *magenta
    crumbs:
      fgColor: *foreground
      bgColor: *cyan
      activeColor: *yellow
    status:
      newColor: *cyan
      modifyColor: *blue
      addColor: *green
      errorColor: *red
      highlightColor: *orange
      killColor: *comment
      completedColor: *comment
    title:
      fgColor: *foreground
      bgColor: *background
      highlightColor: *blue
      counterColor: *magenta
      filterColor: *magenta
  views:
    charts:
      bgColor: default
      defaultDialColors:
        - *blue
        - *red
      defaultChartColors:
        - *blue
        - *red
    table:
      fgColor: *foreground
      bgColor: *background
      cursorFgColor: white
      cursorBgColor: *background
      markColor: darkgoldenrod
      header:
        fgColor: *foreground
        bgColor: *background
        sorterColor: *cyan
    xray:
      fgColor: *foreground
      bgColor: *background
      cursorColor: *current_line
      graphicColor: *blue
      showIcons: false
    yaml:
      keyColor: *magenta
      colonColor: *blue
      valueColor: *foreground
    logs:
      fgColor: *foreground
      bgColor: *background
      indicator:
        fgColor: *foreground
        bgColor: *selection
        toggleOnColor: *magenta
        toggleOffColor: *blue
